services:
  postgres:
    image: postgres:16
    container_name: catalogo_liftit_db
    environment:
      POSTGRES_USER: liftit_admin
      POSTGRES_PASSWORD: liftit1234
      POSTGRES_DB: catalogo_liftit
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
