services:
  postgres:
    image: postgres:16
    container_name: catalogo_vzla_db
    environment:
      POSTGRES_USER: liftit_admin
      POSTGRES_PASSWORD: liftit1234
      POSTGRES_DB: catalogo_vzla
    ports:
      - '5434:5432'
    volumes:
      - postgres_vzla_data:/var/lib/postgresql/data

volumes:
  postgres_vzla_data:
