services:
  postgres:
    image: postgres:16
    container_name: cherry_glam_db
    environment:
      POSTGRES_USER: cherry_admin
      POSTGRES_PASSWORD: cherry1234
      POSTGRES_DB: cherry_glam
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
